apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-app
spec:
  rules:
  - host: "${{values.app_name}}-${{values.app_env}}.test.com"
    http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: python-app
              port:
                number: 8080